version: "3.8"

services:
#  api:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: api
#    ports:
#      - "3000:3000"
#    depends_on:
#      postgres:
#        condition: service_healthy
#    networks:
#      - app-network

  event-source-db:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  nats:
    image: nats:latest
    command: [ "-js" ]        # enable JetStream
    ports:
      - "4222:4222"         # NATS client connections
      - "8222:8222"         # Monitoring UI
    restart: unless-stopped

networks:
  app-network:

volumes:
  postgres_data:
